### PR TITLE
add: black and pylint to github workflow

### PR DESCRIPTION
**Pull request by kausthub-kannan**
## Issue ticket Number:
#5 

## Changes done:
1. Added github/workflow 
2. Configured black and pylint (black to run first and followed by pylint)
3. Added __init__.py
4. Added requirements.txt
5. Added .gitignore

### CODE REVIEW

**Comment by kausthub-kannan** [comment]
@elle-Bee Can try running the workflow manually? I have added black and pre-commit along with which I have added other pre-commit hooks for standard code format. The workflow is not being triggered for some reason even in my fork hence added workflow dispatch to trigger it manually

Thank You

**Comment by elle-Bee** [comment]
Hey @kausthub-kannan I'm seeing that you are working on a branch named `kausthub-kannan:pylint-workflow`.
Have you tried pushing the changes into the main branch of your own fork? Maybe that's the reason why it is not triggering.

**Comment by kausthub-kannan** [comment]
@elle-Bee Thanks for the help, after pushing it to the main the workflow works. Shall I close this PR and create a new one via main branch from my fork?

<a href="https://ibb.co/0ngnKs7">Screenshot-20231212-231954</a>

**Comment by elle-Bee** [comment]
Yes, make try making the PR from the main branch of your fork

**Pull request closed without merging**
