### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Dhruv-Pattel**
added instruction in README.md  file for containerization.

### CODE REVIEW

**Comment by elle-Bee** [comment]
hey @Dhruv-Pattel there seems to be some problem with trailing white spaces in the doc, can you look into it?
image

**Comment by Dhruv-Pattel** [comment]
hey @elle-Bee, in the latest commit, I have removed the white space error. check that out.

**Review by elle-Bee — APPROVED** [review]

**Comment by elle-Bee** [comment]
LGTM

**Comment by elle-Bee** [comment]
Great work done @Dhruv-Pattel! 🚀

**Pull request merged**
