### PR TITLE
add: black and pylint to github workflow

### PR DESCRIPTION
**Pull request by kausthub-kannan**
## Issue ticket Number:
#5 

## Changes done:
1. Added github/workflow
2. Added pre-commit hooks
3. Configured black and pylint (black to run first and followed by pylint)
4. Added requirements.txt

### CODE REVIEW

**Comment by kausthub-kannan** [comment]
@elle-Bee The workflow has been updated. Along with black and pylint I have added other pre-commit hooks for code quality.
Thank you

**Comment by elle-Bee** [comment]
hey @kausthub-kannan i have fixed `Fix end-of-file and trailing whitespace` issue because of which this workflow was failing. Could you please sync up your fork now so that the workflow could re run with the updated code?

**Comment by kausthub-kannan** [comment]
> hey @kausthub-kannan i have fixed `Fix end-of-file and trailing whitespace` issue because of which this workflow was failing. Could you please sync up your fork now so that the workflow could re run with the updated code?

Sure, I will do it in a few minutes. I believe the issue was with docs as there were conflicts which I had to resolve manually.

**Comment by elle-Bee** [comment]
I think the error was with the python-ci.yaml file

**Comment by elle-Bee** [comment]
LGTM
Great work @kausthub-kannan

**Comment by kausthub-kannan** [comment]
Thank you!

**Pull request merged**
